### ISSUE TITLE
The --output-keys option not working?

### ISSUE THREAD

**Issue by laseanb** [andreyvit/json-diff#115]
First off, Thank You for your work on this tool!!!!

While using it I noticed that the `-o` or `--output-keys` option doesn't seem to work in v1.0.3 though it does work in v0.9.1. Running with the verbose option, I noticed that no matter whether I use `-o` or `-x`, the `excludeKeys` always got filled with the args while the `outputKeys` array remained empty.

ie `json-diff -v --output-keys "one" <(echo '{"one":"1","two":"2","three":"3"}') <(echo '{"one":"1","two":"2","four":"4"}')`

Looking at this commit (https://github.com/andreyvit/json-diff/commit/91da5eee0bdfdfc5c416e4ef87cc6a5291fcdfa3?diff=unified), it looks like `#var(outputKeys)` was changed to `#var(excludeKeys)` which makes it so that the args passed to either `-x` or `-o` options always get funneled to `excludeKeys`.

Is this a bug?

**Comment by ewoudenberg** [comment]
Hi, yes, thank you, looks like a typo/bug in the usage section. I'll try to
get to it shortly, unless you'd like to post a PR for it. -Thanks! -Eric

**Comment by laseanb** [comment]
Hey Eric, I just created a PR: https://github.com/andreyvit/json-diff/pull/116
