### ISSUE TITLE
1.0.4 version makes the terminal so messy

### ISSUE THREAD

**Issue by woo94** [andreyvit/json-diff#117]
83f25f491348613b130df727b7e2f6163dec7eec commit add few console.log lines which prints things related to scalarize

This makes the terminal dizzy, causing inconvenience.

If it is not commented by mistake, I think it is necessary to fully explain the intention. As a user who really uses this library, I want to contribute, so I'll write a PR that commented on it.

**Comment by ewoudenberg** [comment]
Thank you so much Woo94! I don't know how I missed that. -Eric
