### ISSUE TITLE
Option to ignore line moved to another line 

### ISSUE THREAD

**Issue by Deph0** [andreyvit/json-diff#21]
I'm trying to diff something that has a lot of lines that are moved, i'd like to be able to ignore these in order to see if something else changed, e.g. spelling or added something new.

incase i'm not making any sense, this is what i want to be able to ignore

```
   myobject: {
     alist: [
+      "something"
       "foobarstuff"
-      "something"
     ]
   }
```

where "something" is the same but just moved down a row, but hasn't changed content.

**Comment by CoryOwens** [comment]
+1
This could probably be accomplished by sorting elements within objects/arrays.

**Comment by Deph0** [comment]
I ended up with using [https://stedolan.github.io/jq/](jq) to sort the elements first (and "beautifying" it).

`jq -S 'def recsort: if type=="array" then [.[]|recsort]|sort elif type=="object" then (.[]) |= recsort else . end; recsort' myJsonFile.json > new.json`

**Comment by CoryOwens** [comment]
Thanks for that script. 
Seems, though, like once you sort and beautify it, you can just use a standard diff, rather than the slower json-diff.

**Comment by Deph0** [comment]
Yeah.. That's why this issue exists :) that extra step isn't ideal and took quite some time to find that tool and get a understanding of their filter-like scripting.

**Comment by ewoudenberg** [comment]
A --sort option has been added to v0.7.0 that sorts array primitives.
