### ISSUE TITLE
feature-request: compare only the structure (not the values)

### ISSUE THREAD

**Issue by flocsy** [andreyvit/json-diff#22]
I'd like to have an option to ignore values, so if I would compare:
a.json:
{"env":"skeleton","key":"foo"}
b.json:
{"env":"dev"}

json-diff --ignore-values a.json b.json

It would give a warning on the missing "key", but not on the different value in "env".

**Comment by FireyFly** [comment]
This issue should be closed since it was resolved in the above PR.
