### ISSUE TITLE
Option to print out all of the JSON file (as well as differences)?

### ISSUE THREAD

**Issue by matatk** [andreyvit/json-diff#24]
I would like to compare two JSON files to see what is different, but also what is the same.

Currently, it seems that json-diff prints out some 'context' lines around diff chunks, but there is no option for printing out all of first.json, even if it is the same as second.json.

Could such an option be added?

**Comment by ewoudenberg** [comment]
The `--full` option has been added in 0.6.0. It outputs the entire object, not just the deltas:
```
$ json-diff  <(echo '[[1,2,3],[4,5,6],3]') <(echo '[[1,2,3],[4,5,6],7]')
 [
   ...
   ...
-  3
+  7
 ]
$ json-diff  --full <(echo '[[1,2,3],[4,5,6],3]') <(echo '[[1,2,3],[4,5,6],7]')
 [
   [
     1
     2
     3
   ]
   [
     4
     5
     6
   ]
-  3
+  7
 ]
```
