### ISSUE TITLE
Request: add instructions for usage in scripts

### ISSUE THREAD

**Issue by cheapsteak** [andreyvit/json-diff#25]
I had to log out what properties the exported package contained to know that it had `diff` and `diffString` 

README could benefit from letting people know this isn't limited to being a commandline tool

**Comment by codeclown** [comment]
While not ideal (especially since they're coffeescript), you can check out the tests to see how to use programmatically.

https://github.com/andreyvit/json-diff/blob/master/test/diff_test.coffee

**Comment by worldsayshi** [comment]
I just added a PR: https://github.com/andreyvit/json-diff/pull/30
