### ISSUE TITLE
Ability to use it in javascript files 

### ISSUE THREAD

**Issue by pransen** [andreyvit/json-diff#28]
Do we have the provision to call "json-diff" from javascript files and use the diff obtained for some further purpose ?

like var jsonDiff = require('json-diff');

**Comment by ashrussell** [comment]
Seconded :) 👍

**Comment by andreyvit** [comment]
Please see [cli.coffee](lib/cli.coffee) for an example of how to do this. Roughly it should be:

    require('json-diff').diffString(a, b)

I would appreciate a PR adding an example to README!

**Comment by worldsayshi** [comment]
I did :)

**Comment by ewoudenberg** [comment]
Implemented (2017)
