### ISSUE TITLE
Ignore certain keys

### ISSUE THREAD

**Issue by TheM1984** [andreyvit/json-diff#36]
Please add an option to filter out certain keys.

Like diff maybe use the capital i as parameter.

For example:
json-diff -I id -I created_at -I updated_at -I random_object_id a.json b.json

Or maybe read a json file with an array of keys to be ignored

json-diff --ignore_file ignore_keys.json

So those keys will be ignored, in the comparison.

It would be a great help in comparing json files across a production and test environment.

**Comment by ewoudenberg** [comment]
This can be accomplished by filtering through egrep, as follows:
```
$ json-diff   <(echo '{"created_at": true, "id": 10}')  <(echo '{"created_at": false, "id":20}')
 {
-  created_at: true
+  created_at: false
-  id: 10
+  id: 20
 }
$ json-diff   <(echo '{"created_at": true, "id": 10}')  <(echo '{"created_at": false, "id":20}')  | egrep -v '\b(created_at|id)\b'
 {
 }
```

**Comment by karlitos** [comment]
Can you please re-open the ticket ? The above solution with `egrep` works only for keys with atomic properties.

### Original
```bash
{
   properties: {
-    _id: {
-      type: "object"
-      properties: {
-        timestamp: {
-          type: "integer"
-        }
-      }
-      additionalProperties: false
-      writeOnly: true
-    }

...
```

### With `egrep -v '\b(_id)\b'`
```bash
 {
   properties: {
-      type: "object"
-      properties: {
-        timestamp: {
-          type: "integer"
-        }
-      }
-      additionalProperties: false
-      writeOnly: true
-    }
```

**Comment by karlitos** [comment]
I made a Pull Request related to this issue https://github.com/andreyvit/json-diff/pull/98

**Comment by ewoudenberg** [comment]
Thank you @karlitos !
