### ISSUE TITLE
False and True values

### ISSUE THREAD

**Issue by axi92** [andreyvit/json-diff#38]
If I change a value from true to false it gives me this output:

```
   ...
   {
-    alive: true
   }
   ...
```
It does not recognize that false was added, only that true is gone

**Comment by FireyFly** [comment]
PR #35 resolves this (and the same for `null`), and will hopefully be merged whenever @andreyvit is around.

**Comment by pjeby** [comment]
Empty strings have the same problem, and #35 didn't fix it.  ;(

**Comment by ewoudenberg** [comment]
This works properly in 0.6.0:
```
$ json-diff   <(echo '{"a": ""}')  <(echo '{"a": false}')
 {
-  a: ""
+  a: false
 }
```
