### ISSUE TITLE
Upgrade cli-color so we are using the dependency version with a license.

### ISSUE THREAD

**Issue by kbradl16** [andreyvit/json-diff#45]
The current version (version 0.1.7) being used of cli-color does not have a license.

**Comment by kbradl16** [comment]
Related to https://github.com/awslabs/aws-cdk/issues/2249.

**Comment by kbradl16** [comment]
https://github.com/aws/aws-cdk/issues/4517

**Comment by ewoudenberg** [comment]
Resolved in 0.6.1
