### ISSUE TITLE
TypeError: Cannot assign to read only property 'name' of function 

### ISSUE THREAD

**Issue by nevf** [andreyvit/json-diff#46]
I'm getting:
```difflib.js:78 Uncaught TypeError: Cannot assign to read only property 'name' of function 'function SequenceMatcher(isjunk, a, b, autojunk) ```

for:
````
 SequenceMatcher = (function() {

    SequenceMatcher.name = 'SequenceMatcher';    // <<== here

````

**Comment by rekenerd** [comment]
Make sure that compiler's target of your application is `es5`.

I was getting the same error when I was using `es2015`.

**Comment by nevf** [comment]
@rekenerd  Thx, but I'm only writing straight es6, no Babel etc

**Comment by jamie-pate** [comment]
compiling to es5 is not a good option, need to add a fork of the `difflib` project and depend on that (or make it a peer dependency so we can choose to use a fork)

**Comment by KishoreGarpati** [comment]
@jamie-pate can you post the fix for this issue to create the patch.

**Comment by jamie-pate** [comment]
I ended up switching to the much faster `variable-diff` but here's the patch 👎 

```
diff --git a/node_modules/difflib/lib/difflib.js b/node_modules/difflib/lib/difflib.js
index 80d250e..ae6e1df 100644
--- a/node_modules/difflib/lib/difflib.js
+++ b/node_modules/difflib/lib/difflib.js
@@ -75,7 +75,7 @@ Class Differ:
 
   SequenceMatcher = (function() {
 
-    SequenceMatcher.name = 'SequenceMatcher';
+    // SequenceMatcher.name = 'SequenceMatcher';
 
     /*
       SequenceMatcher is a flexible class for comparing pairs of sequences of
@@ -737,7 +737,7 @@ Class Differ:
 
   Differ = (function() {
 
-    Differ.name = 'Differ';
+    // Differ.name = 'Differ';
 
     /*
       Differ is a class for comparing sequences of lines of text, and
```

**Comment by ewoudenberg** [comment]
Closing since this pertains to difflib, not json-diff.

**Comment by NayeemGani** [comment]
I currently facing this issue with json-diff package. Which am using in my lambda function.

{
  "errorType": "TypeError",
  "errorMessage": "Cannot assign to read only property 'name' of function 'function O(j,$,ee,L){this.isjunk=j,$==null&&($=\"\"),ee==null&&(ee=\"\"),this.autojunk=L??!0,this.a=this.b=null,this.setSeqs($,ee)}'",
  "trace": [
    "TypeError: Cannot assign to read only property 'name' of function 'function O(j,$,ee,L){this.isjunk=j,$==null&&($=\"\"),ee==null&&(ee=\"\"),this.autojunk=L??!0,this.a=this.b=null,this.setSeqs($,ee)}'",
    "    at <anonymous> (/node_modules/difflib/lib/difflib.js:78:21)",
    "    at Object.<anonymous> (/node_modules/difflib/lib/difflib.js:660:3)",
    "    at exports (/node_modules/difflib/lib/difflib.js:1486:4)",
    "    at /var/task/index.js:1:227",
    "    at <anonymous> (/node_modules/difflib/index.js:1:18)",
    "    at /var/task/index.js:1:227",
    "    at <anonymous> (/node_modules/json-diff/lib/index.js:1:29)",
    "    at /var/task/index.js:1:227",
    "    at Object.<anonymous> (/lambdas/sync-checker/index.ts:2:28)",
    "    at Module._compile (node:internal/modules/cjs/loader:1256:14)"
  ]
}.
