### ISSUE TITLE
json-diff cli always returns error shell status code

### ISSUE THREAD

**Issue by elgalu** [andreyvit/json-diff#51]
```sh
json-diff ....
echo $?
#=> 1
```

**Comment by elgalu** [comment]
Ah exit 1 here, should be 0

https://github.com/andreyvit/json-diff/blob/master/lib/cli.coffee#L48

**Comment by ewoudenberg** [comment]
Resolved in 0.6.1 -- always returns exit code 0 if it does any work. If there's an error or the help message is output we exit with non-zero.
