### ISSUE TITLE
How to also see common keys/values?

### ISSUE THREAD

**Issue by aalexgabi** [andreyvit/json-diff#53]
Is there a way to see common keys/values?

**Comment by NightMachinary** [comment]
I like to use `json-diff` to find what elements have changed in a big array. I like to see the whole changed object when one of its keys change.

**Comment by aalexgabi** [comment]
I propose an option that allows hiding common keys if you want.

**Comment by ewoudenberg** [comment]
The `--full` option has been added in 0.6.0. It outputs the entire object, not just the deltas:
```
$ json-diff  <(echo '[[1,2,3],[4,5,6],3]') <(echo '[[1,2,3],[4,5,6],7]')
 [
   ...
   ...
-  3
+  7
 ]
$ json-diff  --full <(echo '[[1,2,3],[4,5,6],3]') <(echo '[[1,2,3],[4,5,6],7]')
 [
   [
     1
     2
     3
   ]
   [
     4
     5
     6
   ]
-  3
+  7
 ]
```

**Comment by aalexgabi** [comment]
@ewoudenberg That is very nice!
