### ISSUE TITLE
Overlooks type differences of number and string in array

### ISSUE THREAD

**Issue by Durun** [andreyvit/json-diff#56]
json-diff overlooks differences of number and string in array.

For example, when json-diff compares `[1]` with `["1"]`, returns nothing.
```diff
```
expected:
```diff
 [
-  1
+  "1"
 ]
```

**Comment by ewoudenberg** [comment]
This is due to a but in Difflib. I have submitted a PR to fix this (but the last commit there was 2012): https://github.com/qiao/difflib.js/pull/13
