### ISSUE TITLE
input array in deep object,but output object

### ISSUE THREAD

**Issue by halberlink** [andreyvit/json-diff#61]
a.json
`
"settings": {
        "react": {
            "version": "detect" // Tells eslint-plugin-react to automatically detect the version of React to use
        },
        "import/resolver": {
            "node": {
                "extensions": [
                    ".js",
                    ".jsx",
                    ".tsx"
                ]
            },
            // 解决tsconfig下的path别名导致eslint插件无法解决的bug
            "typescript": {
                "directory": "."
            }
        }
 }
`
b.json
`
"settings": {
        "react": {
            "version": "detect" // Tells eslint-plugin-react to automatically detect the version of React to use
        },
        "import/resolver": {
            "node": {
                "extensions": [
                    ".js",
                    ".jsx"
                ]
            },
            // 解决tsconfig下的path别名导致eslint插件无法解决的bug
            "typescript": {
                "directory": "."
            }
        }
 }
`

console.log(jsonDiff.diffString(a, b);
output:

![image](https://user-images.githubusercontent.com/25400591/118606534-1f486300-b7ea-11eb-979e-73a34e6f2883.png)

why extenstions become an object ？

**Comment by ewoudenberg** [comment]
This works properly in 0.6.0:
```
$ cat a.json
{
  "settings": {
    "react": { "version": "detect" },
    "import/resolver": {
      "node": { "extensions": [".js", ".jsx", ".tsx"] },
      "typescript": { "directory": "." }
    }
  }
}
$ cat b.json
{
  "settings": {
    "react": { "version": "detect" },
    "import/resolver": {
      "node": { "extensions": [".js", ".jsx"] },
      "typescript": { "directory": "." }
    }
  }
}
$ json-diff  a.json b.json
 {
   settings: {
     import/resolver: {
       node: {
         extensions: [
           ...
           ...
-          ".tsx"
         ]
       }
     }
   }
 }
$ json-diff --full a.json b.json
 {
   settings: {
     react: {
       version: "detect"
     }
     import/resolver: {
       node: {
         extensions: [
           ".js"
           ".jsx"
-          ".tsx"
         ]
       }
       typescript: {
         directory: "."
       }
     }
   }
 }
```
