### ISSUE TITLE
Breaking change in v0.7.2

### ISSUE THREAD

**Issue by ljharb** [andreyvit/json-diff#79]
https://unpkg.com/browse/json-diff@0.7.2/lib/colorize.js contains the `??` operator (added in #73); v0.7.1 does not.

package.json explicitly says all node versions in `engines.node` (https://unpkg.com/browse/json-diff@0.7.1/package.json), and in npm's semver, v0.8.0 would be a breaking change, but v0.7.2 can only be minor or patch.

Can you publish a v0.7.3 that avoids this operator?

**Comment by ewoudenberg** [comment]
Thank you @ljharb -- I've reverted usage of the ?? operator.

**Comment by ewoudenberg** [comment]
We've reverted usage of the ?? operator.

**Comment by ljharb** [comment]
Thank you for the fast fix!!
