### ISSUE TITLE
Not seeing Date differences

### ISSUE THREAD

**Issue by gehbauerct** [andreyvit/json-diff#80]
The library wasn't noticing differences in dates.  I've forked and here's a link to the commit with my test and fix.
[Fork commit](https://github.com/gehbauerct/json-diff/commit/6a1c57da2b372732436d697fe8b30f5fdde0da70)

**Comment by michelbl** [comment]
I created a PR from this commit : https://github.com/andreyvit/json-diff/pull/106

**Comment by ewoudenberg** [comment]
Fixed in json-diff@1.0.1
