### ISSUE TITLE
add option to print nothing if the two objects are the same

### ISSUE THREAD

**Issue by SheetJSDev** [andreyvit/json-diff#9]
```
$ cat t.json
{"foo":[1,2,3]}
$ json-diff t.json t.json
 undefined
```

Ideally there would be an option (or default behavior) whereby no output would be generated if the objects are the same.

**Comment by subinvarghesein** [comment]
Seems like this issue has been fixed with https://github.com/andreyvit/json-diff/pull/14

@andreyvit Can you release a new npm version with this change?
