### ISSUE TITLE
Marking remains with output-new-only option

### ISSUE THREAD

**Issue by kjdev** [andreyvit/json-diff#91]
There is a case that marking remains when checking the difference of arrays with the output-new-only specification.

When output-new-only is specified, it expects a changed element, so the same element `... ` should also be absent.

``` sh
$ echo '{"test":[1,2]}' > 1.json
$ echo '{"test":[2,3]}' > 2.json
```
``` sh
$ json-diff -n 1.json 2.json
 {
   test: [
-    1
     ...
+    3
   ]
 }
```

> ``` sh
> $ npm list --depth=0 -g
> /usr/local/lib
> `-- json-diff@0.9.0
> ```

expected.

``` 
{
  test: [
    3
  ]
}
```

**Comment by ewoudenberg** [comment]
Sorry,  `--output-new-only ` only applies to new `keys` in an object, not new array elements.
