### ISSUE TITLE
"true" and true are the same in lists

### ISSUE THREAD

**Issue by elpollodiablo** [andreyvit/json-diff#93]
behaves correctly:

    console.log(jsonDiff.diffString({"thisis":true}, {"thisis":"true"}, {full:true}));
    console.log(jsonDiff.diffString([{"thisis":true}], [{"thisis":"true"}], {full:true}));

does not behave correctly:

    console.log(jsonDiff.diffString(["false", true], [false, "true"], {full:true}));
    console.log(jsonDiff.diffString([false, "true"], ["false", true], {full:true}));

**Comment by ewoudenberg** [comment]
Resolved in v1.0.0
